main change lol xd lol xd Assets\Scripts\Player\PlayerStates.cs(3,13): error CS0101: The namespace '<global namespace>' already contains a definition for 'playerStates'  The file 'UserSettings/EditorUserSettings.asset' seems to have merge conflicts. Please open it in a text editor and fix the merge.